### ISSUE TITLE
persistent.tests.test_timestamp.PyAndCComparisonTests.test_strs_equal fails

### ISSUE THREAD

**Issue by mcepl** [zopefoundation/persistent#86]
```
[   15s] ======================================================================
[   15s] FAIL: test_strs_equal (persistent.tests.test_timestamp.PyAndCComparisonTests)
[   15s] ----------------------------------------------------------------------
[   15s] Traceback (most recent call last):
[   15s]   File "/home/abuild/rpmbuild/BUILD/persistent-4.2.4.2/persistent/tests/test_timestamp.py", line 253, in test_strs_equal
[   15s]     self.assertEqual(str(c), str(py))
[   15s] AssertionError: '2008-12-22 15:20:-11.700000' != '2008-12-22 15:20:48.300000'
[   15s] - 2008-12-22 15:20:-11.700000
[   15s] ?                  ^^^ ^
[   15s] + 2008-12-22 15:20:48.300000
[   15s] ?                  ^^ ^
```
[Build log](https://github.com/zopefoundation/persistent/files/2287337/osc-build-log.txt)

This is running on completely normal run-of-the-mill Lenovo Thinkpad T480 with openSUSE Tumbleweed, so of course it is x86_64 architecture. Using persistent-4.2.4.2.tar.gz.

Replacing my comment in #41.

**Comment by jamadden** [comment]
I haven't been able to reproduce this either, but all my test machines are debian based. 


This looks to be the compiler invocation:
```
[   13s] gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -DOPENSSL_LOAD_CONF -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -fPIC -I/usr/include/python3.6m -c persistent/_timestamp.c -o build/temp.linux-x86_64-3.6/persistent/_timestamp.o
[   14s] gcc -pthread -shared -flto -fuse-linker-plugin -ffat-lto-objects -flto-partition=none build/temp.linux-x86_64-3.6/persistent/_timestamp.o -L/usr/lib64 -lpython3.6m -o build/lib.linux-x86_64-3.6/persistent/_timestamp.cpython-36m-x86_64-linux-gnu.so
```

Some of those switches I'm not familiar with. We *may* be doing some things that aren't strictly defined? (I'm not sure) So possibly the switches might make a difference? (There aren't any warnings, but compilers are fickle; I *know* that -ffast-math changes the results.) Can you try compiling with just '-O2'?

Also, do you get the same behaviour on master and with #83? Master fixed at least one case of undefined behaviour, and #83 I'm just curious about :) I wouldn't expect either of them to actually make a difference, though.

**Comment by jamadden** [comment]
The seconds value we're working with is `48.299999952316284` so we may be looking at some math precision issues in C world. FWIW, my C implementation matches the Python example above, so the C example above is (obviously) wrong.

The C version uses `sprintf` with a format string of `"%4.4d-%2.2d-%2.2d %2.2d:%2.2d:%09.6f"`, it's possible we could also be looking at a libc sprintf or locale issue in the final '%09.6f' part.

**Comment by mcepl** [comment]
Using ``gcc-8-2.1.x86_64`` and ``glibc-2.27-6.1.x86_64``, but I don't how to build with different ``CFLAGS``.

When I try ``CFLAGS="-O2" python3 setup.py build`` I still get build with the standard openSUSE CFLAGS. And no, we don't patch ``setup.py`` in any way.

**Comment by jamadden** [comment]
This would be the most direct C test, going straight to the end result and holding the full precision of the literal:
```C
#include <stdio.h>

int main(void)
{
    char buf[128];
    sprintf(buf, "%4.4d-%2.2d-%2.2d %2.2d:%2.2d:%09.6f",
	    2008, 12, 22, 920 / 60, 920 % 60,
	    48.299999952316284);
    printf("%s\n", buf);
    return 0;
}
```

Replace that last constant with `48.29999994020909` to get the actual value its using (on my machine) once the rounding has taken place. (I suggest compiling with all the same flags as the python module.) Both produce "2008-12-22 15:20:48.300000" as expected here. If you get something different, it's an sprintf issue.

You could also adjust `test_strs_equal` to have it print `c.second()` before the `assertEqual`. On my machine, it's returning that `48.29999994020909` value; if you get something different it's the precision issue.

**Comment by mgedmin** [comment]
This is an amazing issue and I _love_ it!

The negative value returned by TimeStamp_sec, well, let's see:

```c
static double
TimeStamp_sec(TimeStamp *self)
{
    unsigned int v;

    v = (self->data[4] * 16777216 + self->data[5] * 65536
     + self->data[6] * 256 + self->data[7]);
    return SCONV * v;
}
```

On a 32-bit platform `unsigned int` is 32 bits.  `self->data[4]` is an `unsigned char`.  255 * 16777216 should still fit in an unsigned int, hm.

What happens, according to the C standard, when you multiply a `double` and an `unsigned int`?

**Comment by mcepl** [comment]
```
c = -11.70000005979091

======================================================================
FAIL: test_strs_equal (persistent.tests.test_timestamp.PyAndCComparisonTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/matej/build/python/python-persistent/persistent-4.3.0/persistent/tests/test_timestamp.py", line 255, in test_strs_equal
    self.assertEqual(str(c), str(py))
AssertionError: '2008-12-22 15:20:-11.700000' != '2008-12-22 15:20:48.300000'
- 2008-12-22 15:20:-11.700000
?                  ^^^ ^
+ 2008-12-22 15:20:48.300000
?                  ^^ ^
```
and the testing program
```
matej@stitny: tmp$ cat test-persistent-86.c
#include <stdio.h>

int main(void)
{
    char buf[128];
    sprintf(buf, "%4.4d-%2.2d-%2.2d %2.2d:%2.2d:%09.6f",
	    2008, 12, 22, 920 / 60, 920 % 60,
	    -11.70000005979091);
    printf("%s\n", buf);
    return 0;
}
matej@stitny: tmp$ gcc -O2 -o test-persistent-86 test-persistent-86.c 
matej@stitny: tmp$ ./test-persistent-86 
2008-12-22 15:20:-11.700000
matej@stitny: tmp$
```

**Comment by mgedmin** [comment]
Hey, the 16777216 constant is an `int`!  There you have it, 32-bit signed overflow is undefined.

**Comment by mgedmin** [comment]
So, would changing that to `16777216U` improve things?  I'm not a native C speaker.

(Can we get a 32-bit Linux platform on Travis?)

**Comment by jamadden** [comment]
I thin using standard sized types like uint _64 would be good. Except Windows may have a problem with that.

**Comment by mcepl** [comment]
> (Can we get a 32-bit Linux platform on Travis?)

openSUSE builds on i586 as well https://build.opensuse.org/package/show/devel:languages:python/python-persistent

**Comment by jamadden** [comment]
We have a 32 bit platform thanks to manylinux. But we don’t run the tests there, perhaps we should.

**Comment by mcepl** [comment]
> We have a 32 bit platform thanks to manylinux. But we don’t run the tests there, perhaps we should.

After switching to working for SUSE I have completely turned around (Saul to Paul kind of) … everybody should run all tests possible.

**Comment by mgedmin** [comment]
I don't think we need a 64-bit int here, we just need to force the arithmetic to be unsigned.

**Comment by mgedmin** [comment]
Yeah, I fail reading comprehension _again_:

> This is running on completely normal run-of-the-mill Lenovo Thinkpad T480 with openSUSE Tumbleweed, so of course it is x86_64 architecture.

How can one get a negative number out of this???

@mcepl since you're currently the only one who can reproduce this, would you mind adding some extra debug printfs like

```c
static double
TimeStamp_sec(TimeStamp *self)
{
    unsigned int v;

    v = (self->data[4] * 16777216 + self->data[5] * 65536
     + self->data[6] * 256 + self->data[7]);
    printf("DEBUG: v = %u, SCONV = %f, result = %f\n", v, SCONV, SCONV * v);   /* <----- */
    return SCONV * v;
}
```

**Comment by jamadden** [comment]
After the merge of #87 I have high hopes that this would be fixed in master now. All the arithmetic is explicitly unsigned after that.

**Comment by jamadden** [comment]
@mcepl I would like to release master as 4.4.0 soon. Do you expect to have time to look at this more soon? Or would it be easier if the changes were released?

**Comment by mcepl** [comment]
@jamadden sorry, I am on vacations so I don't follow my GitHub issues that often. There are the debug prints here:
```
[   37s] ======================================================================
[   37s] FAIL: test_strs_equal (persistent.tests.test_timestamp.PyAndCComparisonTests)
[   37s] ----------------------------------------------------------------------
[   37s] Traceback (most recent call last):
[   37s]   File "/home/abuild/rpmbuild/BUILD/persistent-4.3.0/persistent/tests/test_timestamp.py", line 254, in test_strs_equal
[   37s]     self.assertEqual(str(c), str(py))
[   37s] AssertionError: '2008-12-22 15:20:-11.700000' != '2008-12-22 15:20:48.300000'
[   37s] - 2008-12-22 15:20:-11.700000
[   37s] ?                  ^^^ ^
[   37s] + 2008-12-22 15:20:48.300000
[   37s] ?                  ^^ ^
[   37s] 
[   37s] 
[   37s] ----------------------------------------------------------------------
[   37s] Ran 475 tests in 0.304s
[   37s] 
[   37s] FAILED (failures=1)
[   37s] Test failed: <unittest.runner.TextTestResult run=475 errors=0 failures=1>
[   37s] DEBUG: v = 1968526677, SCONV = 0.000000, result = 27.500000
[   37s] DEBUG: v = 1968526677, SCONV = 0.000000, result = 27.500000
[   37s] DEBUG: v = 1968526677, SCONV = 0.000000, result = 27.500000
[   37s] DEBUG: v = 1968526677, SCONV = 0.000000, result = 27.500000
[   37s] DEBUG: v = 1968526677, SCONV = 0.000000, result = 27.500000
[   37s] DEBUG: v = 1968526677, SCONV = 0.000000, result = 27.500000
[   37s] DEBUG: v = 1968526677, SCONV = 0.000000, result = 27.500000
[   37s] DEBUG: v = 1968526677, SCONV = 0.000000, result = 27.500000
[   37s] DEBUG: v = 3457448669, SCONV = 0.000000, result = -11.700000
[   37s] DEBUG: v = 0, SCONV = 0.000000, result = 0.000000
[   37s] DEBUG: v = 0, SCONV = 0.000000, result = 0.000000
[   37s] DEBUG: v = 0, SCONV = 0.000000, result = 0.000000
[   37s] DEBUG: v = 0, SCONV = 0.000000, result = 0.000000
[   37s] DEBUG: v = 1632476982, SCONV = 0.000000, result = 22.805440
[   37s] error: Test failed: <unittest.runner.TextTestResult run=475 errors=0 failures=1>
[   37s] error: Bad exit status from /var/tmp/rpm-tmp.0Q0Hjp (%check)
[   37s] 
[   37s] 
[   37s] RPM build errors:
[   37s]     Bad exit status from /var/tmp/rpm-tmp.0Q0Hjp (%check)
[   37s] 
[   37s] stitny failed "build python-persistent.spec" at Sat Aug 25 11:52:02 UTC 2018.
[   37s]
```

**Comment by jamadden** [comment]
@mcepl 4.4.0 has been released. Do you still have the problem there? (I will guess that you do.)

> [   37s] DEBUG: v = 3457448669, SCONV = 0.000000, result = -11.700000

SCONV requires more than the default `%f` formatting to see; something like `%1.12f` ought to do it. (and `%2.12f` for `result`).

The value of `v` is correct here. The value for SCONV (renamed to `TS_SECOND_BYTES_BIAS` in 4.4.0 should print as  0.000000013970, and the result should be 48.299999940209, but you're wrapping around. Even if I explicitly type `v` as `uint32_t` and `SCONV` as `float`, I still don't wraparound, nor would I expect to. Now I'm getting curious as to what instructions the compiler is generating for your function.

One difference between the working values (1968526677) and the failing value (3457448669) is that bit 31 (high-order bit of a 32-bit number) is set.

**Comment by mcepl** [comment]
Withi [this patch](https://github.com/zopefoundation/persistent/files/2320618/test_unsigned.patch.txt) I get this ([full build log](https://github.com/zopefoundation/persistent/files/2320619/osc-build-log.txt)):
```
[   13s] ======================================================================
[   13s] FAIL: test_strs_equal (persistent.tests.test_timestamp.PyAndCComparisonTests)
[   13s] ----------------------------------------------------------------------
[   13s] Traceback (most recent call last):
[   13s]   File "/home/abuild/rpmbuild/BUILD/persistent-4.3.0/persistent/tests/test_timestamp.py", line 253, in test_strs_equal
[   13s]     self.assertEqual(str(c), str(py))
[   13s] AssertionError: '2008-12-22 15:20:-11.700000' != '2008-12-22 15:20:48.300000'
[   13s] - 2008-12-22 15:20:-11.700000
[   13s] ?                  ^^^ ^
[   13s] + 2008-12-22 15:20:48.300000
[   13s] ?                  ^^ ^
[   13s] 
[   13s] 
[   13s] ----------------------------------------------------------------------
[   13s] Ran 475 tests in 0.301s
[   13s] 
[   13s] FAILED (failures=1)
[   13s] Test failed: <unittest.runner.TextTestResult run=475 errors=0 failures=1>
[   13s] DEBUG: v = 3457448669, TS_SECOND_BYTES_BIAS = 0.000000, result = -11.700000
[   13s] DEBUG: v = 0, TS_SECOND_BYTES_BIAS = 0.000000, result = 0.000000
[   13s] DEBUG: v = 0, TS_SECOND_BYTES_BIAS = 0.000000, result = 0.000000
[   13s] DEBUG: v = 0, TS_SECOND_BYTES_BIAS = 0.000000, result = 0.000000
[   13s] DEBUG: v = 0, TS_SECOND_BYTES_BIAS = 0.000000, result = 0.000000
[   13s] DEBUG: v = 1632476982, TS_SECOND_BYTES_BIAS = 0.000000, result = 22.805440
[   13s] DEBUG: v = 1968526677, TS_SECOND_BYTES_BIAS = 0.000000, result = 27.500000
[   13s] DEBUG: v = 1968526677, TS_SECOND_BYTES_BIAS = 0.000000, result = 27.500000
[   13s] DEBUG: v = 1968526677, TS_SECOND_BYTES_BIAS = 0.000000, result = 27.500000
[   13s] DEBUG: v = 1968526677, TS_SECOND_BYTES_BIAS = 0.000000, result = 27.500000
[   13s] DEBUG: v = 1968526677, TS_SECOND_BYTES_BIAS = 0.000000, result = 27.500000
[   13s] DEBUG: v = 1968526677, TS_SECOND_BYTES_BIAS = 0.000000, result = 27.500000
[   13s] DEBUG: v = 1968526677, TS_SECOND_BYTES_BIAS = 0.000000, result = 27.500000
[   13s] DEBUG: v = 1968526677, TS_SECOND_BYTES_BIAS = 0.000000, result = 27.500000
[   13s] error: Test failed: <unittest.runner.TextTestResult run=475 errors=0 failures=1>
[   13s] error: Bad exit status from /var/tmp/rpm-tmp.AestvU (%check)
```

**Comment by mcepl** [comment]
With patch just adding ``printf()`` on the top of 4.4.0 I get:
```
[   13s] 
[   13s] ======================================================================
[   13s] ERROR: persistent.tests.test_docs (unittest.loader.ModuleImportFailure)
[   13s] ----------------------------------------------------------------------
[   13s] ImportError: Failed to import test module: persistent.tests.test_docs
[   13s] Traceback (most recent call last):
[   13s]   File "/usr/lib64/python2.7/unittest/loader.py", line 254, in _find_tests
[   13s]     module = self._get_module_from_name(name)
[   13s]   File "/usr/lib64/python2.7/unittest/loader.py", line 232, in _get_module_from_name
[   13s]     __import__(name)
[   13s]   File "/home/abuild/rpmbuild/BUILD/persistent-4.4.0/persistent/tests/test_docs.py", line 30, in <module>
[   13s]     import manuel.capture
[   13s] ImportError: No module named manuel.capture
[   13s] 
[   13s] 
[   13s] ----------------------------------------------------------------------
[   13s] Ran 515 tests in 0.336s
[   13s] 
[   13s] FAILED (errors=1)
[   13s] Test failed: <unittest.runner.TextTestResult run=515 errors=1 failures=0>
[   13s] 0013970, result = 48.679999946617
[   13s] DEBUG: v = 3485365957, TS_SECOND_BYTES_BIAS = 0.000000013970, result = 48.689999948256
[   13s] DEBUG: v = 3486081785, TS_SECOND_BYTES_BIAS = 0.000000013970, result = 48.699999949895
[   13s] DEBUG: v = 3486797613, TS_SECOND_BYTES_BIAS = 0.000000013970, result = 48.709999951534
[   13s] DEBUG: v = 3487513440, TS_SECOND_BYTES_BIAS = 0.000000013970, result = 48.719999939203
[   13s] DEBUG: v = 3488229268, TS_SECOND_BYTES_BIAS = 0.000000013970, result = 48.729999940842
[   13s] DEBUG: v = 3488945096, TS_SECOND_BYTES_BIAS = 0.000000013970, result = 48.739999942482
[   13s] DEBUG: v = 3489660924, TS_SECOND_BYTES_BIAS = 0.000000013970, result = 48.749999944121
[   13s] DEBUG: v = 3490376752, TS_SECOND_BYTES_BIAS = 0.000000013970, result = 48.759999945760
[   13s] DEBUG: v = 3491092580, TS_SECOND_BYTES_BIAS = 0.000000013970, result = 48.769999947399
[   13s] DEBUG: v = 3491808408, TS_SECOND_BYTES_BIAS = 0.000000013970, result = 48.779999949038
[   13s] DEBUG: v = 3492524236, TS_SECOND_BYTES_BIAS = 0.000000013970, result = 48.789999950677
[   13s] DEBUG: v = 3493240064, TS_SECOND_BYTES_BIAS = 0.000000013970, result = 48.799999952316
[   13s] DEBUG: v = 3493955891, TS_SECOND_BYTES_BIAS = 0.000000013970, result = 48.809999939986
[   13s] DEBUG: v = 3494671719, TS_SECOND_BYTES_BIAS = 0.000000013970, result = 48.819999941625
[   13s] DEBUG: v = 3495387547, TS_SECOND_BYTES_BIAS = 0.000000013970, result = 48.829999943264
[   13s] DEBUG: v = 3496103375, TS_SECOND_BYTES_BIAS = 0.000000013970, result = 48.839999944903
[   13s] DEBUG: v = 3496819203, TS_SECOND_BYTES_BIAS = 0.000000013970, result = 48.849999946542
[   13s] DEBUG: v = 3497535031, TS_SECOND_BYTES_BIAS = 0.000000013970, result = 48.859999948181
[   13s] DEBUG: v = 3498250859, TS_SECOND_BYTES_BIAS = 0.000000013970, result = 48.869999949820
[   13s] DEBUG: v = 3498966687, TS_SECOND_BYTES_BIAS = 0.000000013970, result = 48.879999951459
[   13s] DEBUG: v = 3499682514, TS_SECOND_BYTES_BIAS = 0.000000013970, result = 48.889999939129
[   13s] DEBUG: v = 3457448669, TS_SECOND_BYTES_BIAS = 0.000000013970, result = 48.299999940209
[   13s] DEBUG: v = 3458164497, TS_SECOND_BYTES_BIAS = 0.000000013970, result = 48.309999941848
[   13s] DEBUG: v = 3458880325, TS_SECOND_BYTES_BIAS = 0.000000013970, result = 48.319999943487
[   13s] DEBUG: v = 3459596153, TS_SECOND_BYTES_BIAS = 0.000000013970, result = 48.329999945126
[   13s] DEBUG: v = 3460311981, TS_SECOND_BYTES_BIAS = 0.000000013970, result = 48.339999946766
[   13s] DEBUG: v = 3461027809, TS_SECOND_BYTES_BIAS = 0.000000013970, result = 48.349999948405
[   13s] DEBUG: v = 3461743637, TS_SECOND_BYTES_BIAS = 0.000000013970, result = 48.359999950044
[   13s] DEBUG: v = 3462459465, TS_SECOND_BYTES_BIAS = 0.000000013970, result = 48.369999951683
[   13s] DEBUG: v = 3463175292, TS_SECOND_BYTES_BIAS = 0.000000013970, result = 48.379999939352
[   13s] DEBUG: v = 3463891120, TS_SECOND_BYTES_BIAS = 0.000000013970, result = 48.389999940991
[   13s] DEBUG: v = 3464606948, TS_SECOND_BYTES_BIAS = 0.000000013970, result = 48.399999942631
[   13s] DEBUG: v = 3465322776, TS_SECOND_BYTES_BIAS = 0.000000013970, result = 48.409999944270
[   13s] DEBUG: v = 3466038604, TS_SECOND_BYTES_BIAS = 0.000000013970, result = 48.419999945909
[   13s] DEBUG: v = 3466754432, TS_SECOND_BYTES_BIAS = 0.000000013970, result = 48.429999947548
[   13s] DEBUG: v = 3467470260, TS_SECOND_BYTES_BIAS = 0.000000013970, result = 48.439999949187
[   13s] DEBUG: v = 3468186088, TS_SECOND_BYTES_BIAS = 0.000000013970, result = 48.449999950826
[   13s] DEBUG: v = 3468901915, TS_SECOND_BYTES_BIAS = 0.000000013970, result = 48.459999938495
[   13s] DEBUG: v = 3469617743, TS_SECOND_BYTES_BIAS = 0.000000013970, result = 48.469999940135
[   13s] DEBUG: v = 3470333571, TS_SECOND_BYTES_BIAS = 0.000000013970, result = 48.479999941774
[   13s] DEBUG: v = 3471049399, TS_SECOND_BYTES_BIAS = 0.000000013970, result = 48.489999943413
[   13s] DEBUG: v = 0, TS_SECOND_BYTES_BIAS = 0.000000013970, result = 0.000000000000
[   13s] DEBUG: v = 0, TS_SECOND_BYTES_BIAS = 0.000000013970, result = 0.000000000000
[   13s] DEBUG: v = 0, TS_SECOND_BYTES_BIAS = 0.000000013970, result = 0.000000000000
[   13s] DEBUG: v = 0, TS_SECOND_BYTES_BIAS = 0.000000013970, result = 0.000000000000
[   13s] DEBUG: v = 1632476982, TS_SECOND_BYTES_BIAS = 0.000000013970, result = 22.805439988151
[   13s] error: Test failed: <unittest.runner.TextTestResult run=515 errors=1 failures=0>
[   13s] error: Bad exit status from /var/tmp/rpm-tmp.cEmlxZ (%check)
````
[Full build log](https://github.com/zopefoundation/persistent/files/2320787/osc-build-log.txt)

**Comment by mcepl** [comment]
Sorry, I missed there is 4.4.1 already, this is [updated log](https://github.com/zopefoundation/persistent/files/2320792/osc-build-log.txt).

**Comment by jamadden** [comment]
Ah, so cool, it does fix the problem. You're just missing one of the updated test deps from the `test` extra.

**Comment by mcepl** [comment]
Not completely. Passes under python2, but not under python3:
````
[   14s] 
[   14s] ======================================================================
[   14s] FAIL: test_strs_equal (persistent.tests.test_timestamp.PyAndCComparisonTests)
[   14s] ----------------------------------------------------------------------
[   14s] Traceback (most recent call last):
[   14s]   File "/home/abuild/rpmbuild/BUILD/persistent-4.4.1/persistent/tests/test_timestamp.py", line 252, in test_strs_equal
[   14s]     self.assertEqual(str(c), str(py))
[   14s] AssertionError: '2008-12-22 15:20:-11.700000' != '2008-12-22 15:20:48.300000'
[   14s] - 2008-12-22 15:20:-11.700000
[   14s] ?                  ^^^ ^
[   14s] + 2008-12-22 15:20:48.300000
[   14s] ?                  ^^ ^
[   14s] 
[   14s] 
[   14s] ----------------------------------------------------------------------
[   14s] Ran 524 tests in 0.322s
[   14s] 
[   14s] FAILED (failures=1)
[   14s] Test failed: <unittest.runner.TextTestResult run=524 errors=0 failures=1>
[   14s] DEBUG: v = 438334110, TS_SECOND_BYTES_BIAS = 0.000000, result = 6.123457
[   14s] DEBUG: v = 465288123, TS_SECOND_BYTES_BIAS = 0.000000, result = 6.500000
[   14s] DEBUG: v = 468867263, TS_SECOND_BYTES_BIAS = 0.000000, result = 6.550000
[   14s] DEBUG: v = 469225177, TS_SECOND_BYTES_BIAS = 0.000000, result = 6.555000
[   14s] DEBUG: v = 469260968, TS_SECOND_BYTES_BIAS = 0.000000, result = 6.555500
[   14s] DEBUG: v = 469264547, TS_SECOND_BYTES_BIAS = 0.000000, result = 6.555550
[   14s] DEBUG: v = 469264905, TS_SECOND_BYTES_BIAS = 0.000000, result = 6.555555
[   14s] DEBUG: v = 469264941, TS_SECOND_BYTES_BIAS = 0.000000, result = 6.555555
[   14s] DEBUG: v = 469264944, TS_SECOND_BYTES_BIAS = 0.000000, result = 6.555556
[   14s] DEBUG: v = 469264945, TS_SECOND_BYTES_BIAS = 0.000000, result = 6.555556
[   14s] DEBUG: v = 3457448669, TS_SECOND_BYTES_BIAS = 0.000000, result = -11.700000
[   14s] DEBUG: v = 0, TS_SECOND_BYTES_BIAS = 0.000000, result = 0.000000
[   14s] DEBUG: v = 0, TS_SECOND_BYTES_BIAS = 0.000000, result = 0.000000
[   14s] DEBUG: v = 0, TS_SECOND_BYTES_BIAS = 0.000000, result = 0.000000
[   14s] DEBUG: v = 0, TS_SECOND_BYTES_BIAS = 0.000000, result = 0.000000
[   14s] DEBUG: v = 1632476982, TS_SECOND_BYTES_BIAS = 0.000000, result = 22.805440
[   14s] DEBUG: v = 1968526677, TS_SECOND_BYTES_BIAS = 0.000000, result = 27.500000
[   14s] DEBUG: v = 1968526677, TS_SECOND_BYTES_BIAS = 0.000000, result = 27.500000
[   14s] DEBUG: v = 1968526677, TS_SECOND_BYTES_BIAS = 0.000000, result = 27.500000
[   14s] DEBUG: v = 1968526677, TS_SECOND_BYTES_BIAS = 0.000000, result = 27.500000
[   14s] DEBUG: v = 1968526677, TS_SECOND_BYTES_BIAS = 0.000000, result = 27.500000
[   14s] DEBUG: v = 1968526677, TS_SECOND_BYTES_BIAS = 0.000000, result = 27.500000
[   14s] DEBUG: v = 1968526677, TS_SECOND_BYTES_BIAS = 0.000000, result = 27.500000
[   14s] DEBUG: v = 1968526677, TS_SECOND_BYTES_BIAS = 0.000000, result = 27.500000
[   14s] error: Test failed: <unittest.runner.TextTestResult run=524 errors=0 failures=1>
[   14s] error: Bad exit status from /var/tmp/rpm-tmp.6fty47 (%check)
[   14s]
````
[osc-build-log.txt](https://github.com/zopefoundation/persistent/files/2320980/osc-build-log.txt)

**Comment by jamadden** [comment]
Interesting. That function and the interior printing does not use the Python API at all. So I think we're looking at a difference in the compiler and/or compiler flags. (Could we see that output with the `%2.12f` format?)

**Comment by mcepl** [comment]
[Here](https://github.com/zopefoundation/persistent/files/2321102/osc-build-log.txt) you are.

**Comment by jamadden** [comment]
Thanks!

The failing line:

> DEBUG: v = 3457448669, TS_SECOND_BYTES_BIAS = 0.000000013970, result = -11.700000059791

A successful line from earlier in the file:

> DEBUG: v = 3458880325, TS_SECOND_BYTES_BIAS = 0.000000013970, result = 48.319999943487

The `TS_SECOND_BYTES_BIAS` value is correct. Both of the `v` values need 32 bits and begin with 0b110011..... So two very close values are yielding *very* different results.

Here's the bad (-11) value in binary:

```
11000000 00100111 01100110 01100110 01101000 01101000 00000000 00110011
```

And the correct (48.2999) value in binary:

```
01000000 01001000 00100110 01100110 01100101 11100101 11111111 11110011
```

If there's some pattern in the difference, I don't see it.

The compiler args for 2.7 (edited to remove duplicates):
```
gcc -pthread -fno-strict-aliasing -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -DNDEBUG  -DOPENSSL_LOAD_CONF -fwrapv -fPIC -I/usr/include/python2.7 -c persistent/_timestamp.c -o build/temp.linux-x86_64-2.7/persistent/_timestamp.o
[   15s] gcc -pthread -shared build/temp.linux-x86_64-2.7/persistent/_timestamp.o -L/usr/lib64 -lpython2.7 -o build/lib.linux-x86_64-2.7/persistent/_timestamp.so
```

And 3.6:
```
 gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -DOPENSSL_LOAD_CONF -g   -fPIC -I/usr/include/python3.6m -c persistent/_timestamp.c -o build/temp.linux-x86_64-3.6/persistent/_timestamp.o
[   17s] gcc -pthread -shared -flto -fuse-linker-plugin -ffat-lto-objects -flto-partition=none build/temp.linux-x86_64-3.6/persistent/_timestamp.o -L/usr/lib64 -lpython3.6m -o build/lib.linux-x86_64-3.6/persistent/_timestamp.cpython-36m-x86_64-linux-gnu.so
```

Two major things are different that I notice: 

1) Under 2.7, the argument `-fwrapv` is given, which "instructs the compiler to assume that signed arithmetic overflow of addition, subtraction and multiplication wraps around using twos-complement representation. This flag enables some optimizations and disables others." 3.6 does not have that option. I don't *think* we'd be hitting that case, but maybe? It should be pretty easy to compile 3.6 with "-fwrapv" by setting CFLAGS if you want to try that.
2) 3.6 is being linked with LTO, while 2.7 is not. That could change things, though I would think it unlikely. (Then again, I would have thought this whole scenario is unlikely.)

**Comment by mgedmin** [comment]
```
>>> (3457448669 - 2**32) * 0.000000013970
-11.70013521919
```

which is close to -11.700000059791, but not exact, so maybe SCONV is not _precisely_ 0.000000013970?

(still, how on Earth do you get a 32-bit overflow on a 64-bit machine with 64-bit types?)

**Comment by jamadden** [comment]
WHOOPS: Above, I had `TS_SECOND_BYTES_BIAS` defined as `((float)60) / ((float)(1<<16)) / ((float)(1<<16))`, which explains the single precision. If I redefine it as it is in timestamp.c (`#define TS_SECOND_BYTES_BIAS ((double)60) / ((double)(1<<16)) / ((double)(1<<16)))`, I get the expected double precision instructions (still though, I got the expected result using single precision)
```asm
_convert:
LFB4:
	movl	%edi, %edi
	pxor	%xmm0, %xmm0
	movsd	lC1(%rip), %xmm1
	cvtsi2sdq	%rdi, %xmm0
	mulsd	lC0(%rip), %xmm0
	mulsd	%xmm1, %xmm0
	mulsd	%xmm1, %xmm0
	ret
```

**Comment by jamadden** [comment]
>  maybe SCONV is not precisely 0.000000013970?

It's not. Printing 24 bits of precision shows  0.000000013969838619232178 and 
```pycon
>>> (3457448669 - 2**32) * 0.000000013969838619232178
-11.70000005979091
```

**Comment by mgedmin** [comment]
So, `objdump -d ./build/lib.linux-x86_64-2.7/persistent/_timestamp.so` gives me

```
0000000000001410 <TimeStamp_second>:
    1410:	0f b6 47 14          	movzbl 0x14(%rdi),%eax
    1414:	0f b6 57 15          	movzbl 0x15(%rdi),%edx
    1418:	66 0f ef c0          	pxor   %xmm0,%xmm0
    141c:	c1 e0 08             	shl    $0x8,%eax
    141f:	01 d0                	add    %edx,%eax
    1421:	0f b6 57 16          	movzbl 0x16(%rdi),%edx
    1425:	c1 e0 08             	shl    $0x8,%eax
    1428:	01 d0                	add    %edx,%eax
    142a:	0f b6 57 17          	movzbl 0x17(%rdi),%edx
    142e:	c1 e0 08             	shl    $0x8,%eax
    1431:	01 d0                	add    %edx,%eax
    1433:	f2 48 0f 2a c0       	cvtsi2sd %rax,%xmm0
    1438:	f2 0f 59 05 98 0c 00 	mulsd  0xc98(%rip),%xmm0        # 20d8 <month_len+0x1c8>
    143f:	00 
    1440:	e9 bb fa ff ff       	jmpq   f00 <PyFloat_FromDouble@plt>
    1445:	90                   	nop
    1446:	66 2e 0f 1f 84 00 00 	nopw   %cs:0x0(%rax,%rax,1)
    144d:	00 00 00 
```

(as you can see, the TimeStamp_sec was inlined).  AFAIU all the 32-bit operations on %eax implicitly zero-extend the results to full 64-bits in %rax, so there's no possibility of overflow in this function _as compiled by my compliler_.

**Comment by jamadden** [comment]
I get very similar results on macOS with both clang (the default compiler) and gcc 8 with no CFLAGS; if I use my usual optimizing CFLAGS, I get the AVX variants instead of the SSE instructions.

**Comment by mgedmin** [comment]
Same from `docker run -ti --rm opensuse/tumbleweed bash`:
```
    15d0:	0f b6 47 14          	movzbl 0x14(%rdi),%eax
    15d4:	0f b6 57 15          	movzbl 0x15(%rdi),%edx
    15d8:	66 0f ef c0          	pxor   %xmm0,%xmm0
    15dc:	c1 e0 08             	shl    $0x8,%eax
    15df:	01 d0                	add    %edx,%eax
    15e1:	0f b6 57 16          	movzbl 0x16(%rdi),%edx
    15e5:	c1 e0 08             	shl    $0x8,%eax
    15e8:	01 d0                	add    %edx,%eax
    15ea:	0f b6 57 17          	movzbl 0x17(%rdi),%edx
    15ee:	c1 e0 08             	shl    $0x8,%eax
    15f1:	01 d0                	add    %edx,%eax
    15f3:	f2 48 0f 2a c0       	cvtsi2sd %rax,%xmm0
    15f8:	f2 0f 59 05 18 0c 00 	mulsd  0xc18(%rip),%xmm0        # 2218 <_fini@@Base+0x32c>
    15ff:	00 
    1600:	e9 8b fa ff ff       	jmpq   1090 <PyFloat_FromDouble@plt>
```

**Comment by mgedmin** [comment]
And here's `objdump -d /usr/lib64/python3.6/site-packages/persistent/_timestamp.cpython-36m-x86_64-linux-gnu.so` (also Tumbleweed, python3-persistent version 4.3.0):
```
    25c0:	0f b6 47 14          	movzbl 0x14(%rdi),%eax
    25c4:	0f b6 57 15          	movzbl 0x15(%rdi),%edx
    25c8:	66 0f ef c0          	pxor   %xmm0,%xmm0
    25cc:	c1 e0 08             	shl    $0x8,%eax
    25cf:	01 d0                	add    %edx,%eax
    25d1:	0f b6 57 16          	movzbl 0x16(%rdi),%edx
    25d5:	c1 e0 08             	shl    $0x8,%eax
    25d8:	01 d0                	add    %edx,%eax
    25da:	0f b6 57 17          	movzbl 0x17(%rdi),%edx
    25de:	c1 e0 08             	shl    $0x8,%eax
    25e1:	01 d0                	add    %edx,%eax
    25e3:	f2 0f 2a c0          	cvtsi2sd %eax,%xmm0
    25e7:	f2 0f 59 05 29 0c 00 	mulsd  0xc29(%rip),%xmm0        # 3218 <_fini@@Base+0x350>
    25ee:	00 
    25ef:	e9 8c fa ff ff       	jmpq   2080 <PyFloat_FromDouble@plt>
```

**Comment by mgedmin** [comment]
HEY HEY HEY HEY HEY HEEEEYYYYY  SPOT THE DIFFERENCE!

```
    25e3:	f2 0f 2a c0          	cvtsi2sd %eax,%xmm0
```

This converts a 32-bit %eax, while all the others convert a 64-bit %rax.

:sparkles: BUG FOUND :sparkles:  now somebody explain why it gets compiled this way?

**Comment by jamadden** [comment]
Thanks for the tip about docker!

I can duplicate the error compiling the file from scratch in a docker image with the compiler args specified above.

If I add `-fwrapv`, what Python 2.7 compiles with by default, the error goes away. The offending line becomes `cvtsi2sdq       %rax, %xmm0`.

**Comment by jamadden** [comment]
It's the `-O2` that triggers it. Without -O2 (and without `-fwrapv`) the code is "correct".

**Comment by jamadden** [comment]
This is looking like it may be a packaging problem with python3 on opensuse itself.

CPython wants to have `-fwrapv` in its build [by default](https://github.com/python/cpython/blob/master/configure#L6683). But, if I'm looking at the right place, the RPM for building CPython on opensuse [exports $OPT (line 282)](https://build.opensuse.org/package/view_file/openSUSE:Factory/python3/python3-base.spec?expand=1) and overrides this check entirely. So unless the RPM variable `optflags` already has `-fwrapv` in it, the build of python itself and all its extension modules won't have -fwrapv and will thus be subtlety broken.  I don't know where to look for the definition of that variable.

**Comment by mgedmin** [comment]
I've reproduced the miscompilation on https://godbolt.org/z/HtYwXC

Note that if I replace the multiplication by `0x100` etc. with `<< 8` etc, the code gets compiled correctly.

I think when you multiply an `unsigned char` by an `int` constant like `0x1000000`, you get an `int`, and not an `unsigned`.

So, it's a bug in our code and not a compiler bug.

**Comment by jamadden** [comment]
Indeed, if i change the definition of TS_SECOND_BYTES_BIAS to an explicit double constant with the value we expect it to have:
```c
static const double TS_SECOND_BYTES_BIAS =  0.000000013969838619232178;
```

The code is *still* miscompiled when given -O2 and not given `-fwrapv`:
```asm
_TimeStamp_second:
LFB87:
	movzbl	20(%rdi), %eax
	pxor	%xmm0, %xmm0
	movzbl	21(%rdi), %edx
	sall	$8, %eax
	addl	%edx, %eax
	movzbl	22(%rdi), %edx
	sall	$8, %eax
	addl	%edx, %eax
	movzbl	23(%rdi), %edx
	sall	$8, %eax
	addl	%edx, %eax
	cvtsi2sd	%eax, %xmm0 ; Still EAX
	mulsd	lC3(%rip), %xmm0
	jmp	_PyFloat_FromDouble
```

**Comment by jamadden** [comment]
If I remove the `static const` part so the compiler has to look up the variable, we can see for sure that that the mistake is happening well before the actual multiplication; it's happening in the inlined arithmetic that unpacks the bytes into an unsigned int (and now I think I see what you were saying above, I was thinking about a different constant than you were)
```
_TimeStamp_second:
LFB87:
	movzbl	20(%rdi), %eax
	pxor	%xmm0, %xmm0
	movzbl	21(%rdi), %edx
	sall	$8, %eax
	addl	%edx, %eax
	movzbl	22(%rdi), %edx
	sall	$8, %eax
	addl	%edx, %eax
	movzbl	23(%rdi), %edx
	sall	$8, %eax
	addl	%edx, %eax
	cvtsi2sd	%eax, %xmm0
	mulsd	_TS_SECOND_BYTES_BIAS(%rip), %xmm0
	jmp	_PyFloat_FromDouble
```

Sure enough, changing the constants used in `TS_UNPACK_UINT32_FROM_BYTES` to have the `U` suffix does change the register usage:
```asm
_TimeStamp_second:
LFB87:
	movzbl	20(%rdi), %eax
	pxor	%xmm0, %xmm0
	movzbl	21(%rdi), %edx
	sall	$8, %eax
	addl	%edx, %eax
	movzbl	22(%rdi), %edx
	sall	$8, %eax
	addl	%edx, %eax
	movzbl	23(%rdi), %edx
	sall	$8, %eax
	addl	%edx, %eax
	cvtsi2sdq	%rax, %xmm0
	mulsd	_TS_SECOND_BYTES_BIAS(%rip), %xmm0
	jmp	_PyFloat_FromDouble
```

I would have sworn that hex literals were unsigned by default, I thought I looked that up before I made the change, but it seems that's not true.

**Comment by mgedmin** [comment]
Heh, yeah, sorry for not being sufficiently explicit.

**Comment by mcepl** [comment]
> But, if I'm looking at the right place, the RPM for building CPython on opensuse exports $OPT (line 282) and overrides this check entirely.

You are right. It is really strange, but CPython doesn't provide a configuration option to just **add** building option, you can just completely **replace** everything, so we had to add ``-fwrapv`` to our ``OPTS`` manually. Thank you very much, nobody was able to discover this packaging bug for quite some time we have it there.

**Comment by jamadden** [comment]
Cool! For complete circular reference, here is the PR for the build change: 
https://build.opensuse.org/request/show/632918
